# Generated by Django 5.1.5 on 2025-03-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_seller_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
